security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        app_society_provider:
            entity:
                class: App\Entity\Society
                property: email

        chain_provider:
            chain:
                providers:
                    - app_user_provider
                    - app_society_provider

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: chain_provider

            form_login:
                login_path: app_login
                check_path: app_login

            logout:
                path: app_logout
                target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:

        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }

        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/society, roles: ROLE_SOCIETY }
        - { path: ^/user, roles: ROLE_USER }