# config/services.yaml

# Put parameters here that don't change between machines (e.g. secret tokens)
# config/services.yaml

parameters:
    # Dossier pour les CV
    cv_directory: '%kernel.project_dir%/public/uploads/cvs'
    
    # Paramètres pour la vidéo (URL et Chemin local)
    app.motivational_video_embed_url: 'https://www.youtube.com/embed/votre_id'
    app.motivational_video_path: '%kernel.project_dir%/public/videos/khadamni-intro.mp4'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'